import Head from 'next/head'
import styles from '../styles/Home.module.css'

import { server } from '../config'

export default function Home({ data }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <h1>TheNewboston Network Status</h1>
        </div>
        <div>
          {Object.entries(data).map(([key, response]) => {
            return (
              <div className={styles.separator}>
                <p>{key} {response.value?.url} </p>
                <p>Expiry {response.expire} <span className={response.value?.data ? styles.up : styles.down}>{response.value?.data ? "OK" : "DOWN"}</span></p>
              </div>
            )
          })}
        </div>

      </main>
    </div>
  )
}

export async function getServerSideProps(context) {
  context.res.setHeader(
    'Cache-Control',
    'public, s-maxage=10, stale-while-revalidate=59'
  )
  const res = await fetch(`${server}/api/getStatus`)
  const data = await res.json()

  if (!data) {
    return {
      notFound: true,
    }
  }

  return {
    props: {
      data
    }, // will be passed to the page component as props
  }
}
